export enum ActionType {
  NEXT_MONTH = "NEXT_MONTH",
  PREVIOUS_MONTH = "PREVIOUS_MONTH",
  RESET_MONTH = "RESET_MONTH",
  SET_SELECTED_DAY = "SET_SELECTED_DAY",
  SET_SELECTED_EVENT = "SET_SELECTED_EVENT",
  SHOW_EVENT_MODAL = "SHOW_EVENT_MODAL",
}
